config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save { email.downcase! }
  validates :name, 
            presence: true, 
            length: { maximum: 50 }
  validates :email, 
            presence: true, 
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
  validates :password,
            presence: true,
            length: { minimum: 6 }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "🇺🇦"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "User profile created successfully!"
      redirect_to @user
    else 
      render 'new'
    end
  end

  private 

    def user_params
      params.require(:user).permit(:email, 
                                   :name, 
                                   :password, 
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title
  def full_title(page_title = '')
    base_title = 'Random Thoughts'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Based on <a href="https://www.learnenough.com/ruby-on-rails-7th-edition">Ruby on Rails Tutorial by Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'random thoughts', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Help', help_path %></li>
        <li><%= link_to 'Login', '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params.to_yaml) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% unless @user.errors.empty? %>
<div id="error_explanation">
  <div class="alert alert-danger">
  The form contains <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :div, message, class: "alert alert-#{type}" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Here is how it works:</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Random Thoughts</h1>
  <p>Have you ever had this feeling - that you had a great idea - you MUST remember?</p>
  <p>Until you forgot what the idea was 5 minutes later?</p>
  <p>Random Thoughts will help you solve this problem.</p>
  <%= link_to 'Sign up', signup_path, class: 'btn btn-lg btn-primary' %>
</div>

app/views/users/new.html.erb
<%= provide(:title, "Sign up") %>
<h1>Sign up</h1>
<h2>Create your account - the world is waiting for your first random thought!</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'shared/error_messages' %>

    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %> 

<div class="row">
  <aside class="col-md-4"> 
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %> <%= @user.name %>
      </h1> 
    </section>
  </aside> 
  </div>